menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- categories
- tag
- search

#- twitter
#- tagcloud
excerpt_link: Read More

twitter:
  username: imcoddy
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-41226530-1
rss: imcoddy
